Dict dictionary = create_dict("dictionary");
add_word(&dictionary, "anthropomorphism", "Attributing distinctly human characteristics to nonhuman processes.");
add_word(&dictionary, "antifragile", "Some things benefit from shocks; they thrive and grow when exposed to volatility, randomness, disorder, stressors, risk, and uncertainty.");
add_word(&dictionary, "rationality", "Characteristic of thinking and acting optimally.");
add_word(&dictionary, "parsimony", "Refers to the quality of economy or frugality in the use of resources.");
add_word(&dictionary, "epistemology", "A theory of knowledge, especially with regard to its methods, validity, and scope, and the distinction between justified belief and opinion.");
add_word(&dictionary, "lateralus", "The affliction of illusion of inescapable cyclicality. Example: The failure to recognize one's growth, inability to dream of unprecedented things, ceding to self-reinforcing systems, being jaded to hope, waiting for nonexistent chickens to hatch from nonexistent eggs.");

Dict principles = create_dict("principles");
add_word(&principles, "occams_razor", "When several theories are able to explain the same observations, Occam's razor suggests the one making the fewest assumptions.");
add_word(&principles, "kolmogorov_complexity", "The length of the shortest possible program to output a given object.");
add_word(&principles, "kardashev_scale", "A measure of a civilization's level of technological advancement based on the amount of energy used for communication.");
add_word(&principles, "levenshtein_distance", "A string metric for measuring the difference between two sequences, or comparing the similarity of two words.");
add_word(&principles, "dunbars_number", "A suggested cognitive limit of 150, to the number of people with whom one can maintain stable social relationships.");
add_word(&principles, "bechdel_test", "A method for evaluating the portrayal of women in fiction. It asks whether a work features at least two women who talk to each other about something other than a man.");
add_word(&principles, "finkbeiner_test", "A checklist proposed to help journalists avoid gender bias in media articles about women in science.");
add_word(&principles, "ship_of_theseus", "A thought experiment that raises the question of whether an object that has had all of its components replaced remains fundamentally the same object.");
add_word(&principles, "goodharts_law", "When a measure becomes a target, it ceases to be a good measure.");

// Dict time = create_dict("time");
// add_word(&time, "causality", "Relationship between a cause and an effect, where the effect is a direct consequence of the cause.");
// add_word(&time, "eternal_return", "A theory that the universe and all existence and energy has been recurring, and will continue to recur, in a self-similar form an infinite number of times across infinite time or space.");
// add_word(&time, "super_now", "A type of prediction taking things that are happening now and imagining that the future will be just like now, only “more extreme.”");
// add_word(&time, "teleology", "The study of things that happen for the sake of their future consequences. The fallacious meaning of it is that events are the result of future events.");
// add_word(&time, "prediction", "Statement or claim that a particular event will occur in the future in more certain terms than a forecast.");
// add_word(&time, "equinox", "Twice a year, around 20 March and 22 September, when daytime and nighttime are of approximately equal duration all over the planet.");
// add_word(&time, "solstice", "Twice a year, when either hemisphere has the most sunlight of the year(summer solstice) or the least sunlight of the year(winter solstice) for any place other than the Equator.");

Dict space = create_dict("space");
add_word(&space, "entropy", "Or Irreversibility, a lack of order or predictability; gradual decline into disorder.");
add_word(&space, "false_vacuum", "An hypothetical vacuum(space devoid of matter) that is not entirely stable. If a small region of the universe reached a more stable vacuum, this change would spread.");
add_word(&space, "great_filter", "With no evidence of intelligent life other than ourselves, it appears that the process of starting with a star and ending with \"advanced explosive lasting life\" must be unlikely.");
add_word(&space, "von_neumann_probes", "Or Universal Assemblers, A spacecraft capable of replicating itself.");
add_word(&space, "final_anthropic_principle", "Intelligent information-processing must come into existence in the Universe, and, once it comes into existence, will never die out.");
add_word(&space, "mathematical_universe_hypothesis", "Or Tegmark Universe, our external physical reality is a mathematical structure consisting of starting conditions with rules about how they are to evolve. Any universe that corresponds to a logically coherent mathematical object exists, but universes exist “more”(in some sense) in proportion to their underlying mathematical simplicity.");
add_word(&space, "liminality", "The quality of ambiguity, or disorientation, that occurs during a middle stage, or a threshold. Liminal places can range from borders and frontiers to crossroads and airports, which people pass through but do not live in.");

Dict sociology = create_dict("sociology");
add_word(&sociology, "philanthropy", "The desire to promote the welfare of others.");
add_word(&sociology, "effective_altruism", "A philosophy and social movement that uses evidence and reasoning to determine the most effective ways to benefit others.");
add_word(&sociology, "utilitarianism", "A moral philosophy that says that what matters is the sum of everyone's well-being, or the \"greatest good for the greatest number\".");
add_word(&sociology, "hedonism", "A moral philosophy that says that the highest goal is to maximize pleasure(esp. pleasure minus pain), or that the only things that are good or bad are concious states.");
add_word(&sociology, "altruism", "Actions undertaken for the benefit of other people. Example: If you do something to feel good about helping people, or even to be a better person in some spiritual sense, it isn't truly altruism.");
add_word(&sociology, "hedonic_treadmill", "A tendency of humans to quickly return to a relatively stable level of happiness despite major positive or negative events or life changes.");
add_word(&sociology, "hedonistic_imperative", "The Hedonistic Imperative outlines how genetic engineering and nanotechnology will abolish suffering in all sentient life.");
add_word(&sociology, "longtermism", "A design philosophy to build products for the long term.");
add_word(&sociology, "the_veil_of_ignorance", "Imagine yourself behind a veil of ignorance. Behind this veil, you know nothing of yourself and your natural abilities, position in society, sex, race, nationality, or individual tastes. Behind such a veil of ignorance all individuals are simply specified as rational, free, and morally equal beings. Although you could never actually eliminate all of your personal biases and prejudices, you would need to take steps at least to minimize them.");
add_word(&sociology, "behavioral_sink", "A term used to describe the collapse in behavior(stress, alienation, hostility, sexual perversion, parental incompetence, and rabid violence) which resulted from overcrowdedness in an experiment on mice, drawing parallels with societal collapse found in the human Megalopolis.");
add_word(&sociology, "groupthink", "Tendency of humans to tend to agree with each other, and hold back objections or dissent even when the group is wrong.");
add_word(&sociology, "paradox_of_tolerance", "States that if a society is tolerant without limit, its ability to be tolerant is eventually seized or destroyed by the intolerant.");

// Dict psychology = create_dict("psychology");
// add_word(&psychology, "derealization", "An alteration in the perception or experience of the external world so that it seems unreal.");
// add_word(&psychology, "solipsism_syndrome", "A psychological state in which a person feels that the world is not external to his or her mind.");
// add_word(&psychology, "qualia", "Term used in philosophy to refer to individual instances of subjective, conscious experience. The pain of a headache, or the taste of wine.");
// add_word(&psychology, "suggestibility", "A form of misattribution where ideas suggested by a questioner are mistaken for memory.");
// add_word(&psychology, "priming", "Psychological phenomenon that consists in early stimulus influencing later thoughts and behavior.");
// add_word(&psychology, "confabulation", "Remembering something that never actually happened.");
// add_word(&psychology, "salience", "The perceptual quality by which an observable thing stands out relative to its environment.");
// add_word(&psychology, "method_of_loci", "A method of memory enhancement which uses visualizations with the use of spatial memory to quickly and efficiently recall information.");

Dict philosophy = create_dict("philosophy");
add_word(&philosophy, "ontology", "The topic concerning the nature of being.");
add_word(&philosophy, "gestalt", "The conscious experience must be considered globally, as having a reality of its own, independent of the parts.");
add_word(&philosophy, "dasein", "German word for 'existence', literally meaning 'being there'.");
add_word(&philosophy, "deliberate_practice", "Focused, consistent and goal-oriented training. It favours quality over quantity. It knows not all practice is created equal.");
add_word(&philosophy, "perfect_duty", "Perfect duties are duties that are blameworthy if not met, as they are a basic required duty for a human being.");
add_word(&philosophy, "maxim", "A concise expression of a fundamental moral rule or principle.");
add_word(&philosophy, "hermeneutics", "The branch of knowledge that deals with interpretation.");
add_word(&philosophy, "ubermensch", "The one who seeks out hardship and creates new values.");
add_word(&philosophy, "the_last_man", "The one who seeks comfort and alms.");
add_word(&philosophy, "saudade", "A deep emotional state of nostalgic or profound melancholic longing for an absent something or someone that one loves. Saudade was once described as \"the love that remains\" after someone is gone.");
add_word(&philosophy, "wabisabi", "Acknowledgement that nothing lasts, nothing is finished, and that nothing is perfect.");

Dict linguistics = create_dict("linguistics");
add_word(&linguistics, "gematria", "A cipher that assigns numerical value to a word, name, or phrase in the belief that words or phrases with identical numerical values bear some relation to each other.");
add_word(&linguistics, "palindrome", "A word, number, or other sequence of characters which reads the same backward as forward.");
add_word(&linguistics, "ambigram", "A word, art form or other symbolic representation whose elements retain meaning when viewed or interpreted from a different direction, perspective, or orientation.");
add_word(&linguistics, "leitmotif", "A short, constantly recurring musical phrase associated with a particular person, place, or idea.");

Dict personalities = create_dict("personalities");
add_word(&personalities, "extraversion_introversion", "Represents the source and direction of a person’s energy expression. An extravert’s source and direction of energy expression is mainly in the external world, while an introvert has a source of energy mainly in their own internal world.");
add_word(&personalities, "sensing_intuition", "Represents the method by which someone perceives information. Sensing means that a person mainly believes information they receive directly from the external world. Intuition means that a person believes mainly information they receive from the internal or imaginative world.");
add_word(&personalities, "thinking_feeling", "Represents how a person processes information. Thinking means that a person makes a decision mainly through logic. Feeling means that, as a rule, they make a decision based on emotion, i.e. based on what they feel they should do.");
add_word(&personalities, "judging_perceiving", "Represents how a person implements the information they have processed. Judging means that a person organizes all of his life events and, as a rule, sticks to his plans. Perceiving means that they are inclined to improvise and explore alternative options.");

Dict green_anarchism = create_dict("green_anarchism");
add_word(&green_anarchism, "veganism", "A philosophy and way of living which seeks to prevent all forms of exploitation of, and cruelty to, other animals for food, clothing or any other purpose.");
add_word(&green_anarchism, "health", "A state of complete physical, mental and social well-being and not merely the absence of disease or infirmity.");
add_word(&green_anarchism, "animal_liberation_front", "An international, leaderless resistance that engages in removing animals from laboratories and farms, destroying facilities, arranging safe houses and veterinary care, and operating sanctuaries where the animals subsequently live.");
add_word(&green_anarchism, "animal_advocacy", "Promotion of the interests of animals, generally. Includes work for animal rights and animal welfare.");
add_word(&green_anarchism, "animal_rights", "Refers to the position that the interests of nonhuman animals, including their interest in not suffering, should be afforded the same consideration as the interests of humans and that nonhuman animals have rights and inherent value independent of their usefulness to humans.");
add_word(&green_anarchism, "commodification", "The conversion of a living being, principle, or natural environment into an \"object\" that is used, exchanged, or consumed for profit or other desired gain.");
add_word(&green_anarchism, "debarking", "The surgical removal and manipulation of tissue in a dog's vocal cords to drastically quiet his or her natural bark. Debarking does not address the underlying reasons that a dog may be barking excessively, and the dog will continue to bark, albeit more quietly or silently.");
add_word(&green_anarchism, "dark_greens", "The ones who believe that environmental problems are an inherent part of industrialized civilization, and seek radical political change.");
add_word(&green_anarchism, "draize_test", "Infamous and excruciating eye-irritation test for household products and cosmetics in which drops of a substance are placed in the eyes of rabbits, causing the animals ulcers, blindness, and other injuries before they are ultimately killed.");
add_word(&green_anarchism, "ecofeminism", "Ecofeminist thinkers draw on the concept of gender to theorize on the relationship between humans and the natural world.");
add_word(&green_anarchism, "flowerpot_technique", "A technique used in sleep deprivation studies designed to allow NREM sleep but prevent REM sleep.");
add_word(&green_anarchism, "forced_molting", "The egg-industry practice of artificially inducing hens to molt by depriving them of food for several days to two weeks when their egg production has declined.");
add_word(&green_anarchism, "light_greens", "The ones who see protecting the environment first and foremost as a personal responsibility, focusing on environmentalism as a lifestyle choice.");
add_word(&green_anarchism, "rape_rack", "The industry term referring to the contraptions in which cows and pigs are restrained while they are forcibly inseminated.");
add_word(&green_anarchism, "speciesism", "Discrimination on the basis of species, oppression and judgment of an animal on the basis of that animal's species or that animal's non-membership in a species. The belief in human superiority over other animals or certain nonhuman animals' superiority over others.");
add_word(&green_anarchism, "veal_crate", "Small crate in which a calf being raised for veal is confined and tied up. The calf's movement within the crate is intentionally restricted to limit the strengthening of muscle, and an insufficient diet is provided intentionally to keep the cow anemic.");

Dict collapsologism = create_dict("collapsologism");
add_word(&collapsologism, "uncivilisation", "It is to accept the world for what it is and to make our home here, rather than dreaming of relocating to the stars, or existing in a Man-forged bubble and pretending to ourselves that there is nothing outside it to which we have any connection at all.");
add_word(&collapsologism, "dark_mountaineers", "Artists who generally ascribe to the idea that climate collapse cannot be stopped or reversed, a forum in which one can be honest about their sense of dread and loss.");
add_word(&collapsologism, "inhumanism", "A shifting of emphasis and significance from man to not-man, the rejection of human solipsism and recognition of the transhuman magnificence.");
add_word(&collapsologism, "anthropocene", "A proposed epoch dating from the commencement of significant human impact on Earth's geology and ecosystems, including, but not limited to, anthropogenic climate change.");
add_word(&collapsologism, "simple_pastoral", "Merely another of our many vehicles of escape from reality, that doesn’t interrogate civilisation's main driving forces, but instead focuses on returning to rural simplicity.");
add_word(&collapsologism, "object_oriented_ontology", "A school of thought that rejects the privileging of human existence over the existence of nonhuman objects, that objects exist independently of human perception and are not ontologically exhausted by their relations with humans.");
add_word(&collapsologism, "freudian_death_drive", "The hypothesis of a death instinct, the task of which is to lead organic life back into the inanimate state.");
add_word(&collapsologism, "agrilogistics_paradox", "A maniacal urge to live, and to diminish stimulation, that ends up being self-destructive, generating mass extinction, through global warming, that it was designed to avoid.");
add_word(&collapsologism, "existential_risk", "An event that could cause human extinction or permanently and drastically curtail humanity's potential.");
add_word(&collapsologism, "strong_longtermism", "The primary determinant of the value of our actions is the effects of those actions on the very long-run future.");
add_word(&collapsologism, "the_hinge_of_history_hypothesis", "The hypothese that we are living at the most influential time ever.");
add_word(&collapsologism, "negative_emissions", "Divided into “natural” and “technological”  categories, these strategies aim to remove carbon from the atmosphere, however, there remains no evidence that either branch is feasible despite their inclusion in climate modeling. The large majority of IPCC models (344/400 as of 2019) feature theoretical negative emissions.");
add_word(&collapsologism, "carbon_capture", "A technological negative emissions solution that aims to remove carbon from the air, storing it as inert material. Small units exist at high cost, and it remains unclear whether large scale deployment is possible or desirable.");
add_word(&collapsologism, "carbon_budget", "An attempt to provide the world with a means of tracking emissions with goals set based on projected temperature rise. Most models are not believed to accurately account for feedback loops.");
add_word(&collapsologism, "feedback_loops", "The results of global warming are complex. Much of the destruction caused by warming also contributes: the albedo effect, forest fires, melting ice, and ocean acidification all mean more greenhouse gases and less places for carbon to go. It remains unclear how these systems will interact with ongoing anthropogenic warming.");
add_word(&collapsologism, "albedo_effect", "Warming caused by the disappearance of ice which previously reflect heat back into space.");
add_word(&collapsologism, "scientific_reticence", "A phenomenon where scientists failed to emphasize many the more dramatic results of the study of global warming over concerns of reception.");
add_word(&collapsologism, "fossil_capitalism", "A theory suggesting the modern economy is actually just a system that runs on fossil fuel.");
add_word(&collapsologism, "tragedy_of_the_commons", "A situation in a shared-resource system where individual users, acting independently according to their own self-interest, behave contrary to the common good of all users by depleting or spoiling the shared resource through their collective action.");

Dict aeropunk = create_dict("aeropunk");
add_word(&aeropunk, "compressed_air_energy_storage", "A way to store energy generated at one time for use at another time using compressed air.");
add_word(&aeropunk, "carbon_fiber_tank", "Brittle and can split under sufficient stress, but creates no shrapnel when it does so. Carbon-fiber tanks safely hold air at a pressure somewhere around 4500 psi, making them comparable to steel tanks.");
add_word(&aeropunk, "stirling_engine", "A quiet heat engine that is operated by a cyclic compression and expansion and a flywheel, generating no emissions.");
add_word(&aeropunk, "the_paris_compressed_air_power_network", "The city of Paris once had an extensive network for distributing power by compressed air which served more than 10,000 customers and remained in use for 100 years.");
add_word(&aeropunk, "bicycle_with_shaft", "Experimental bicyle design that used a shaft connecting the crank to the back wheel instead of a drive chain.");
add_word(&aeropunk, "rectenna", "A circuit that produces a voltage by harvesting the energy from the electromagnetic fields around us trough an antenna.");

Dict biases = create_dict("biases");
add_word(&biases, "actorobserver_bias", "Tendency to overemphasize the influence of their personality and underemphasize the influence of their situation.");
add_word(&biases, "attentional_bias", "Tendency to neglect relevant data when making judgments of a correlation or association.");
add_word(&biases, "choicesupportive_bias", "Tendency to retroactively ascribing to one's choices to be more informed than they were when they were made.");
add_word(&biases, "confirmation_bias", "Tendency to interpret information in a way that confirms one's preconceptions.");
add_word(&biases, "congruence_bias", "Tendency to test hypotheses exclusively through direct testing, in contrast to tests of possible alternative hypotheses.");
add_word(&biases, "regressive_bias", "Tendency to remember high values and high likelihoods/probabilities/frequencies as lower than they actually were and low ones as higher than they actually were. Based on the evidence, memories are not extreme enough.");
add_word(&biases, "egocentric_bias", "Tendency to claim more responsibility for themselves for the results of a joint action than an outside observer would. Recalling the past in a self-serving manner. Like remembering one's exam grades as being better than they were.");
add_word(&biases, "impact_bias", "Tendency to overestimate the length or the intensity of the impact of future feeling states.");
add_word(&biases, "information_bias", "Tendency to seek information even when it cannot affect action.");
add_word(&biases, "modesty_bias", "Tendency to blame failures on oneself while attributing successes to situational factors; opposite of self-serving bias.");
add_word(&biases, "moodcongruent_bias", "Tendency to recall information congruent with one's current mood.");
add_word(&biases, "omission_bias", "Tendency to judge harmful actions as worse, or less moral, than equally harmful omissions.");
add_word(&biases, "selfserving_bias", "Tendency to attribute successes to internal characteristics while blaming failures on outside forces. It may also manifest itself as a tendency for people to evaluate ambiguous information in a way beneficial to their interests.");
add_word(&biases, "status_quo_bias", "Tendency to like things to stay relatively the same.");
add_word(&biases, "superiority_bias", "Tendency to overestimating one's desirable qualities, and underestimating undesirable qualities, relative to other people. Also known as the Lake Wobegon effect.");
add_word(&biases, "survivorship_bias", "Tendency of focusing on what has survived to the present and ignoring what must have been lost.");
add_word(&biases, "trait_ascription_bias", "Tendency for people to view themselves as relatively variable in terms of personality, behavior and mood while viewing others as much more predictable.");
add_word(&biases, "unit_bias", "Tendency to want to finish a given unit of a task or an item with strong effects on the consumption of food in particular.");
add_word(&biases, "exposuresuspicion_bias", "Tendency to steer the search for causes based on the knowledge of a subject's disease in a medical study.");
add_word(&biases, "stereotypical_bias", "Tendency to distort memories towards stereotypes. \"Black-sounding\" names being misremembered as names of criminals.");
add_word(&biases, "zerorisk_bias", "Preference for reducing a small risk to zero over a greater reduction in a larger risk.");
add_word(&biases, "authority_bias", "Tendency to attribute greater accuracy to the opinion of an authority figure and be more influenced by that opinion.");
add_word(&biases, "correspondence_bias", "Tendency to overestimate the contribution of lasting traits and dispositions, as opposed to situational effects, in determining people's behavior.");
add_word(&biases, "obsequiousness_bias", "Tendency to alter responses in the direction they perceive desired by the investigator.");
add_word(&biases, "unacceptability_bias", "Tendency of evading questions that may embarrass or invade privacy.");
add_word(&biases, "projection_bias", "Tendency to assume that others share the same or similar thoughts, beliefs, values, or positions.");
add_word(&biases, "consistency_bias", "Tendency to incorrectly remember one's past attitudes and behaviour as resembling present attitudes and behaviour.");
add_word(&biases, "hindsight_bias", "Tendency to see past events as predictable, based on knowledge of later events. Also known as the \"I-knew-it-all-along\" effect.");
add_word(&biases, "optimism_bias", "Tendency to be over-optimistic about the outcome of planned actions.");
add_word(&biases, "outcome_bias", "Tendency to judge a decision by its eventual outcome instead of based on the quality of the decision at the time it was made.");
add_word(&biases, "positive_bias", "Tendency to test hypotheses with positive rather than negative examples, thus risking to miss obvious disconfirming tests.");
add_word(&biases, "positive_outcome_bias", "Tendency to overestimate the probability of good things happening to them.");

Dict groupthink_biases = create_dict("groupthink_biases");
add_word(&groupthink_biases, "conformity_bias", "Tendency to behave similarly to others in a group, even if doing so goes against your own judgment.");
add_word(&groupthink_biases, "ingroup_bias", "Tendency to give preferential treatment to others they perceive to be members of their own groups.");
add_word(&groupthink_biases, "homogeneity_bias", "Tendency of people to see members of their own group as being relatively more varied than members of other groups.");
add_word(&groupthink_biases, "shared_information_bias", "Tendency for group members to spend more time and energy discussing information that all members are already familiar with (i.e., shared information), and less time and energy discussing information that only some members are aware of.");
add_word(&groupthink_biases, "bandwagon_fallacy", "Assuming that an idea has merit simply because many people believe it or practice it.");
add_word(&groupthink_biases, "abilene_paradox", "When a group of people collectively decide on a course of action that is counter to the preferences of many or all of the individuals in the group.");

Dict effects = create_dict("effects");
add_word(&effects, "ambiguity_effect", "Tendency to avoid options for which missing information makes the probability seem \"unknown\".");
add_word(&effects, "bizarreness_effect", "Tendency to remember bizarre material better than common material.");
add_word(&effects, "bystander_effect", "Tendency for individuals to less likely offer help in an emergency situation when other people are present.");
add_word(&effects, "context_effect", "That cognition and memory are dependent on context, such that out-of-context memories are more difficult to retrieve than in-context memories.");
add_word(&effects, "example", "Recall time and accuracy for a work-related memory will be lower at home, and vice versa.");
add_word(&effects, "contrast_effect", "Enhancement or diminishment of a weight or other measurement when compared with recently observed contrasting object.");
add_word(&effects, "crossrace_effect", "Tendency for people of one race to have difficulty identifying members of a race other than their own.");
add_word(&effects, "dunningkruger_effect", "When people are incompetent in the strategies they adopt to achieve success and satisfaction, they suffer a dual burden, not only do they reach erroneous conclusions and make unfortunate choices, but their incompetence robs them of the ability to realize it. Instead, they are left with the mistaken impression that they are doing just fine.");
add_word(&effects, "false_consensus_effect", "Tendency for people to overestimate the degree to which others agree with them.");
add_word(&effects, "forer_effect", "Tendency to give high accuracy ratings to descriptions of their personality that supposedly are tailored specifically for them, but are in fact vague and general enough to apply to a wide range of people. Also known as the Barnum Effect. Like Horoscopes.");
add_word(&effects, "motivated_cognition", "Tendency to process information toward conclusions that suit some end or goal.");
add_word(&effects, "generation_effect", "That self-generated information is remembered best. People are better able to recall memories of statements that they have generated than similar statements generated by others.");
add_word(&effects, "google_effect", "Tendency to forget information that can be found readily online by using Internet search engines.");
add_word(&effects, "halo_effect", "Tendency for a person's positive or negative traits to \"spill over\" from one area of their personality to another in others' perceptions of them.");
add_word(&effects, "hostile_media_effect", "Tendency to perceive news coverage as biased against your position on an issue.");
add_word(&effects, "humor_effect", "That humorous items are more easily remembered than non-humorous ones, which might be explained by the distinctiveness of humor, the increased cognitive processing time to understand the humor, or the emotional arousal caused by the humor.");
add_word(&effects, "lake_wobegon_effect", "Tendency to report flattering beliefs about oneself and believe that one is above average.");
add_word(&effects, "listlength_effect", "A smaller percentage of items are remembered in a longer list, but as the length of the list increases, the absolute number of items remembered increases as well.");
add_word(&effects, "mere_exposure_effect", "Tendency to express undue liking for things merely because they are familiar with them.");
add_word(&effects, "misinformation_effect", "Memory becoming less accurate because of interference from post-event information.");
add_word(&effects, "modality_effect", "That memory recall is higher for the last items of a list when the list items were received via speech than when they were received through writing.");
add_word(&effects, "overconfidence_effect", "Tendency of being more certain than is justified, given your priors and the evidence available.");
add_word(&effects, "partlist_cueing_effect", "That being shown some items from a list and later retrieving one item causes it to become harder to retrieve the other items.");
add_word(&effects, "picture_superiority_effect", "The notion that concepts that are learned by viewing pictures are more easily and frequently recalled than are concepts that are learned by viewing their written word form counterparts.");
add_word(&effects, "positivity_effect", "That older adults favor positive over negative information in their memories.");
add_word(&effects, "primacy_effect", "Tendency to weigh initial events more than subsequent events.");
add_word(&effects, "processing_effect", "That information that takes longer to read, and is processed with more difficulty, is more easily remembered.");
add_word(&effects, "pseudocertainty_effect", "Tendency to make risk-averse choices if the expected outcome is positive, but make risk-seeking choices to avoid negative outcomes.");
add_word(&effects, "recency_effect", "Tendency to weigh recent events more than earlier events.");
add_word(&effects, "selfrelevance_effect", "That memories relating to the self are better recalled than similar information relating to others.");
add_word(&effects, "spacing_effect", "That information is better recalled if exposure to it is repeated over a long span of time rather than a short one.");
add_word(&effects, "spotlight_effect", "Tendency to overestimate the amount that other people notice your appearance or behavior.");
add_word(&effects, "subadditivity_effect", "Tendency to judge probability of the whole to be less than the probabilities of the parts.");
add_word(&effects, "suffix_effect", "Diminishment of the recency effect because a sound item is appended to the list that the subject is not required to recall.");
add_word(&effects, "telescoping_effect", "Tendency to perceive recent events to have occurred more remotely and remote events appear to have occurred more recently.");
add_word(&effects, "testing_effect", "The fact that you more easily remember information you have read by rewriting it instead of rereading it.");
add_word(&effects, "underconfidence_effect", "State of being more uncertain than is justified, given your priors and the evidence you are aware of.");
add_word(&effects, "verbatim_effect", "That the \"gist\" of what someone has said is better remembered than the verbatim wording. This is because memories are representations, not exact copies.");
add_word(&effects, "von_restorff_effect", "Tendency to remember an item that \"stands out like a sore thumb\", more than other items.");
add_word(&effects, "zeigarnik_effect", "That uncompleted or interrupted tasks are remembered better than completed ones.");
add_word(&effects, "focusing_effect", "Tendency of placing too much importance on one aspect of an event; causes error in accurately predicting the utility of a future outcome.");
add_word(&effects, "endowment_effect", "Tendency to demand much more to give up an object than they would be willing to pay to acquire it.");
add_word(&effects, "nextinline_effect", "That a person in a group has diminished recall for the words of others who spoke immediately before himself, if they take turns speaking.");
add_word(&effects, "matthew_effect", "Whoever has will be given more; whoever does not have, even what they have will be taken from them.");

Dict fallacies = create_dict("fallacies");
add_word(&fallacies, "conjunction_fallacy", "Assumption that specific conditions are more probable than general ones.");
add_word(&fallacies, "detached_lever_fallacy", "Assumption that something simple for one system will be simple for others.");
add_word(&fallacies, "gamblers_fallacy", "Assumption that individual random events are influenced by previous random events. Example: I've flipped heads with this coin five times consecutively, so the chance of tails coming out on the sixth flip is much greater than heads.");
add_word(&fallacies, "mind_projection_fallacy", "Assumption that the way you see the world reflects the way the world really is.");
add_word(&fallacies, "typical_mind_fallacy", "Assumption that other people are more like you than they actually are.");
add_word(&fallacies, "fallacy_of_gray", "Assumption that because nothing is certain, everything is equally uncertain. It does not take into account that some things are more certain than others.");
add_word(&fallacies, "the_sophisticate", "\"The world isn't black and white. No one does pure good or pure bad. Therefore, no one is better than anyone else.\" The Zetet: \"Knowing only gray, you conclude that all grays are the same shade. You mock the simplicity of the two-color view, yet you replace it with a one-color view.\"");
add_word(&fallacies, "planning_fallacy", "Underestimating task-completion times.");
add_word(&fallacies, "sunk_cost_fallacy", "Letting past investments interfere with decision-making in the present.");
add_word(&fallacies, "giant_cheesecake_fallacy", "Occurs when an argument leaps directly from capability to actuality, without considering the necessary intermediate of motive.");
add_word(&fallacies, "narrative_fallacy", "A vulnerability to over-interpretation and our predilection for compact stories over raw truths.");
add_word(&fallacies, "scales_of_justice_fallacy", "Error of using a simple polarized scheme for deciding a complex issue/ each piece of evidence about the question is individually categorized as supporting exactly one of the two opposing positions.");
add_word(&fallacies, "top_1_fallacy", "Related to not taking into account the idea that a small sample size is not always reflective of a whole population and that sample populations with certain characteristics, e.g. made up of repeat job seekers, are not reflective of the whole population.");
add_word(&fallacies, "fallacy_of_relative_privation", "Error of thinking that if something is worse than the problem currently being discussed, then the problem currently being discussed isn't that important at all. In other words: nothing matters if it's not literally the worst thing happening");
add_word(&fallacies, "toupe_fallacy", "All toupées look fake, I've never seen one that I couldn't tell was fake.");

Dict illusions = create_dict("illusions");
add_word(&illusions, "asymmetric_insight", "Tendency to perceive the knowledge of their peers to surpass their peers' knowledge of them.");
add_word(&illusions, "control", "Tendency to believe they can control or at least influence outcomes that they clearly cannot.");
add_word(&illusions, "external_agency", "Tendency to perceive self-generated preferences as instead being caused by insightful, effective and benevolent agents.");
add_word(&illusions, "truth_effect", "Tendency to identify as true statements familiar statements over unfamiliar ones.");
add_word(&illusions, "clustering", "Tendency to perceive patterns where actually none exist.");
add_word(&illusions, "frequency", "Tendency to notice something everywhere after having learnt about it. Also known as the Baader-Meinhof Phenomenon.");
add_word(&illusions, "transparency", "Tendency to overestimate others' ability to know them, and they also overestimate their ability to know others. Misleading impression that your words convey more to others than they really do.");
add_word(&illusions, "antiinductiveness", "The idea that the market would stop being efficient if everyone acted like it already was efficient. For example, a vote in a democracy, the more people that believe their vote counts towards the outcome of an election, the less their votes count.  Also known as the Reverse Tinkerbell effect.");
add_word(&illusions, "antiepistemology", "Bad explicit beliefs about rules of reasoning, usually developed in the course of protecting an existing false belief");

Dict beliefs = create_dict("beliefs");
add_word(&beliefs, "belief", "The mental state in which an individual holds a proposition to be true.");
add_word(&beliefs, "priors", "The beliefs an agent holds regarding a fact, hypothesis or consequence, before being presented with evidence.");
add_word(&beliefs, "alief", "An independent source of emotional reaction which can coexist with a contradictory belief. Example The fear felt when a monster jumps out of the darkness in a scary movie is based on the alief that the monster is about to attack you, even though you believe that it cannot.");
add_word(&beliefs, "proper_belief", "Requires observations, gets updated upon encountering new evidence, and provides practical benefit in anticipated experience.");
add_word(&beliefs, "improper_belief", "Is a belief that isn't concerned with describing the territory. Note that the fact that a belief just happens to be true doesn't mean you're right to have it. If you buy a lottery ticket, certain that it's a winning ticket (for no reason), and it happens to be, believing that was still a mistake.");
add_word(&beliefs, "belief_in_belief", "Where it is difficult to believe a thing, it is often much easier to believe that you ought to believe it. Were you to really believe and not just believe in belief, the consequences of error would be much more severe. When someone makes up excuses in advance, it would seem to require that belief, and belief in belief, have become unsynchronized.");
add_word(&beliefs, "a_priori", "Knowledge which we can be sure of without any empirical evidence(evidence from our senses). So, knowledge that you could realize if you were just a mind floating in a void unconnected to a body.");

Dict arguments = create_dict("arguments");
add_word(&arguments, "ad_baculum", "Argument relying on an appeal to fear or a threat.");
add_word(&arguments, "ad_ignorantiam", "Argument relying on people's ignorance.");
add_word(&arguments, "ad_populum", "Argument relying on sentimental weakness.");
add_word(&arguments, "ad_verecundiam", "Argument relying on the the words of an \"expert\", or authority.");
add_word(&arguments, "ex_silentio", "Argument relying on ignorance.");
add_word(&arguments, "ex_nihilo", "An argument that bears no relation to the previous topic of discussion.");
add_word(&arguments, "non_sequitur", "An inference that does not follow from established premises or evidence.");

Dict responses = create_dict("responses");
add_word(&responses, "akrasia", "State of acting against one's better judgment.");
add_word(&responses, "connotation", "Emotional association with a word.");
add_word(&responses, "intransigence", "Refusal to change one's views or to agree about something.");
add_word(&responses, "inferential_distance", "Gap between the background knowledge and epistemology of a person trying to explain an idea, and the background knowledge and epistemology of the person trying to understand it.");
add_word(&responses, "straw_man", "Creating a false or made up scenario and then attacking it. Painting your opponent with false colors only deflects the purpose of the argument.");
add_word(&responses, "steel_man", "To steelman is to address the strongest possible variant or the most charitable interpretation of an idea, rather than the most available phrasings.");
add_word(&responses, "red_herring", "A diversion from the active topic.");
add_word(&responses, "rationalization", "Starts from a conclusion, and then works backward to arrive at arguments apparently favouring that conclusion. Rationalization argues for a side already selected.");
add_word(&responses, "dogpiling", "A disagreement wherein one person says something wrong or offensive, and a large number of people comment in response to tell them how wrong they are, and continue to disparage the original commenter beyond any reasonable time limit.");
add_word(&responses, "grandstanding", "An action that is intended to make people notice and admire you, behaving in a way that makes people pay attention to you instead of thinking about more important matters.");
add_word(&responses, "whataboutism", "An attempt to discredit an opponent's position by charging them with hypocrisy without directly refuting or disproving their argument.");

Dict buddhism = create_dict("buddhism");
add_word(&buddhism, "ahimsa", "Cause no injury, do no harm. Referred to as nonviolence, and it applies to all living beings—including all animals.");
add_word(&buddhism, "sunyata", "Or Void, a meditative dwelling, an emancipation of the mind by emptiness being consequent upon the realization that \"this world is empty of self or anything pertaining to self\". Form is emptiness, emptiness is form. Emptiness is not separate from form, form is not separate from emptiness. Whatever is form is emptiness, whatever is emptiness is form.");
add_word(&buddhism, "samatha", "Turning our attention to an idea/conception. For instance turning our attention to a geometrical figure, a blue circle. We will focus our attention to this blue circle and ceaselessly, tirelessly, confine it to the vision of this blue circle. We deal here with an exercise of attention that is taking place in continuity, a bit as if finally, the blue circle was self-existing, was something continuous.");
add_word(&buddhism, "wu_wei", "A concept literally meaning non-action, non-doing or non-forcing, in the sense of not striving, often considering the search for immortality secondary, laughable, or harmful.");
add_word(&buddhism, "anicca", "The first of the three marks of existence, the doctrine of impermanence asserts that all of conditioned existence, without exception, is \"transient, evanescent, inconstant\".");
add_word(&buddhism, "anatta", "The second of the three marks of existence, the doctrine of non-self asserts that there is no unchanging, permanent self, soul or essence in living beings.");
add_word(&buddhism, "dukkha", "The third of the three marks of existence, the doctrine of suffering includes physical and mental sufferings of birth, aging, illness, dying.");

Dict paramis = create_dict("paramis");
add_word(&paramis, "dana_parami", "Abandonment of possessions by making donations.");
add_word(&paramis, "sila_parami", "Control of actions and speech to avoid unwholesome actions.");
add_word(&paramis, "nekkhamma_parami", "Renunciation of the lay life in favour of the solitary life.");
add_word(&paramis, "panna_parami", "Development of knowledge and understanding through study and analytical reflection. To teach knowledge to others. To use one's wisdom for a maximum of benefits.");
add_word(&paramis, "viriya_parami", "Effort to work as much as possible for the good of others, even at the risk of one's life.");
add_word(&paramis, "khanti_parami", "Establishment of an always perfect tolerance, irrespective of the actions and words of others towards oneself.");
add_word(&paramis, "sacca_parami", "Truthfulness (to say only what is right).");
add_word(&paramis, "adhitthana_parami", "Decision to devote oneself to beneficial actions and to remain steadfast on it.");
add_word(&paramis, "metta_parami", "Maintaining a state of mind turned to the happiness of others, to practise love for all beings without exception.");
add_word(&paramis, "upekkha_parami", "Rejection of hatred and worship. Not to follow any particular idea. Maintaining the mind in equanimity.");

Dict ascetisms = create_dict("ascetisms");
add_word(&ascetisms, "pamsukula", "Abandonned robes, wearing only second hand clothes.");
add_word(&ascetisms, "tecivarika", "Three robes, having only 3 sets of clothes.");
add_word(&ascetisms, "ekasanika", "A single meal, eating only a single serving, and no between-meals snacks.");
add_word(&ascetisms, "pattapindika", "Everything within the bowl, using a single recipient for a meal, this somehow ties in with eating no meals including indigestible parts, such as bones.");
add_word(&ascetisms, "arannika", "To remain in the forest, dwelling in places away from inhabited areas, such as cities.");
add_word(&ascetisms, "rukkhamula", "To remain beneath a tree, renouncing the shelter of a roof.");
add_word(&ascetisms, "abbhokasika", "To remain on the bare earth without shelter, dwelling on a bare, unsheltered spot.");
add_word(&ascetisms, "susanika", "To remain among charnels, dwell near graveyards, or nearby the dead.");
add_word(&ascetisms, "yathasantatika", "To sleep at the alloted spot, \"One must know how to be fully contented with the conditions we benefit with and what we get\"");
add_word(&ascetisms, "nesajjika", "To renonce to the lying posture, training into always remaining seated, including at time of rest.");

Dict dark_patterns = create_dict("dark_patterns");
add_word(&dark_patterns, "bait_and_switch", "You set out to do one thing, but a different, undesirable thing happens instead.");
add_word(&dark_patterns, "confirmshaming", "Confirmshaming is the act of guilting the user into opting into something. The option to decline is worded in such a way as to shame the user into compliance.");
add_word(&dark_patterns, "disguised_ads", "Adverts that are disguised as other kinds of content or navigation, in order to get you to click on them.");
add_word(&dark_patterns, "forced_continuity", "When your free trial with a service comes to an end and your credit card silently starts getting charged without any warning.");
add_word(&dark_patterns, "friend_spam", "The product asks for your email, or social media permissions, under the pretence it will be used for a desirable outcome (e.g. finding friends), but then spams all your contacts in a message that claims to be from you.");
add_word(&dark_patterns, "hidden_costs", "You get to the last step of the checkout process, only to discover some unexpected charges have appeared, e.g. delivery charges, tax, etc.");
add_word(&dark_patterns, "misdirection", "The design purposefully focuses your attention on one thing in order to distract you attention from another.");
add_word(&dark_patterns, "price_comparison_prevention", "The retailer makes it hard for you to compare the price of an item with another item, so you cannot make an informed decision.");
add_word(&dark_patterns, "privacy_zuckering", "You are tricked into publicly sharing more information about yourself than you really intended to.");
add_word(&dark_patterns, "roach_motel", "The design makes it very easy for you to get into a certain situation, but then makes it hard for you to get out of it (e.g. a subscription).");
add_word(&dark_patterns, "sneak_into_basket", "You attempt to purchase something, but somewhere in the purchasing journey the site sneaks an additional item into your basket, often through the use of an opt-out radio button or checkbox on a prior page.");
add_word(&dark_patterns, "trick_questions", "You respond to a question, which, when glanced upon quickly appears to ask one thing, but if read carefully, asks another thing entirely.");

Dict development = create_dict("development");
add_word(&development, "nih_syndrome", "Or Not Invented Here, to avoid using already existing products, research, standards, or knowledge because of their external origins or costs.");
add_word(&development, "antipattern", "A common response to a recurring problem that is usually ineffective and risks being highly counterproductive.");
add_word(&development, "worse_is_better", "The idea that quality does not necessarily increase with functionality. Software that is limited, but simple to use, may be more appealing to the user and market than the reverse.");
add_word(&development, "dogfood", "A way for an organization to demonstrate confidence in its own products, by using the product itself. A way to test it in real-world usage, acting as quality control and a kind of testimonial advertising.");
add_word(&development, "stovepipe", "A system that has the potential to share data or functionality with other systems but which does not.");
add_word(&development, "the_cathedral_model", "The source code is available with each software release, but code developed between releases is restricted to an exclusive group of developers.");
add_word(&development, "the_bazaar_model", "The source code is developed over the Internet in view of the public.");
add_word(&development, "xy_problem", "You want to do X, and you think Y is the best way of doing so. Instead of asking about X, you ask about Y.");
add_word(&development, "second_system_effect", "The tendency of small, elegant, and successful systems, to be succeeded by over-engineered, bloated systems, due to inflated expectations and overconfidence.");
add_word(&development, "benevolent_dictator_for_life", "A open-source software development practice where project founders retain the final say in disputes or arguments within the community.");
add_word(&development, "yak_shaving", "Refers to a task, that leads you to perform another related task and so on, and so on — all distracting you from your original goal.");
add_word(&development, "sybil_attack", "An attacker subverts the reputation system of a P2P network by creating a large number of pseudonymous identities and uses them to gain a disproportionately large influence.");

Dict unix_primitives = create_dict("unix_primitives");
add_word(&unix_primitives, "cd", "Changes directory.");
add_word(&unix_primitives, "ls", "Lists content of directory.");
add_word(&unix_primitives, "cat", "Reads content of files sequentially.");
add_word(&unix_primitives, "grep", "Searches text for matches of a regular expression.");
add_word(&unix_primitives, "tail", "Displays the tail end of a file or data.");

Dict celestial_navigation = create_dict("celestial_navigation");
add_word(&celestial_navigation, "zenith", "The imaginary point directly above a particular location, opposite to the apparent gravitational force at that location.");
add_word(&celestial_navigation, "azimuth", "The angle offset between the north vector and target's vector on the horizontal plane.");
add_word(&celestial_navigation, "longitude", "The east-west position of a point on the Earth's surface.");
add_word(&celestial_navigation, "latitude", "The north-south position of a point on the Earth's surface.");
add_word(&celestial_navigation, "nautical_mile", "Defined as 1852 meters, or one minute of angle along a meridian on the Earth.");
add_word(&celestial_navigation, "lan", "Local Apparent Noon.");
add_word(&celestial_navigation, "nsl", "Noon sight latitude.");
add_word(&celestial_navigation, "gha", "Greenwich hour angle.");
add_word(&celestial_navigation, "sun_altitude_offset", "4 seconds off is equal to 1 nautical mile.");

Dict jisho_sailing = create_dict("jisho_sailing");
add_word(&jisho_sailing, "", "Harbour");
add_word(&jisho_sailing, "", "Sailing");
add_word(&jisho_sailing, "", "Mast");
add_word(&jisho_sailing, "", "Bow");
add_word(&jisho_sailing, "", "Stern");
add_word(&jisho_sailing, "", "Rigging");
add_word(&jisho_sailing, "", "Starboard side");
add_word(&jisho_sailing, "", "Port side");
add_word(&jisho_sailing, "", "Yacht");

Dict jisho_vegan = create_dict("jisho_vegan");
add_word(&jisho_vegan, "", "Buddhist cuisine often has vegan options.");
add_word(&jisho_vegan, "", "Tofu is often served as an option in soups.");
add_word(&jisho_vegan, "", "Soy Milk is available in most konbinis.");
add_word(&jisho_vegan, "", "Edamame are immature soy beans, often found as a snack in pubs.");
add_word(&jisho_vegan, "", "Miso is a typical ingredient in soups, but often combined with non vegan options.");
add_word(&jisho_vegan, "", "Sesame is often used in vegetarian options.");
add_word(&jisho_vegan, "", "Eryngii mushroom skewer often available in places with yakitori.");
add_word(&jisho_vegan, "", "Enoki");
add_word(&jisho_vegan, "", "Tempeh is a soy product. I have never encountered it in Japan, but it cannot hurt to know how to read it.");
add_word(&jisho_vegan, "", "Konbu is a type of kelp, used in soup broths.");
add_word(&jisho_vegan, "", "Dashi is a type of soup base.");
add_word(&jisho_vegan, "", "A kelp-based soup broth.");

Dict technology_links = create_dict("technology_links");
add_word(&technology_links, "death_to_bullshit", "http://deathtobullshit.com");
add_word(&technology_links, "calm_technology", "https://calmtech.com");
add_word(&technology_links, "worrydreams_ref", "http://worrydream.com/refs");
add_word(&technology_links, "the_long_site", "https://gwern.net/About#long-site");
add_word(&technology_links, "the_indie_web", "https://indieweb.org");
add_word(&technology_links, "sustainable_web", "https://sustainablewebmanifesto.com");
add_word(&technology_links, "local_first_software", "https://www.inkandswitch.com/local-first.html");
add_word(&technology_links, "paper_phone", "http://specialprojects.studio/project/paper-phone");
add_word(&technology_links, "lot2046", "https://www.lot2046.com");
add_word(&technology_links, "c2 wiki", "http://wiki.c2.com/?StartingPoints");

Dict hardware_links = create_dict("hardware_links");
add_word(&hardware_links, "fairphone", "https://fairphone.com/en");
add_word(&hardware_links, "pi_top", "https://pi-top.com");
add_word(&hardware_links, "librem_13", "https://puri.sm");
add_word(&hardware_links, "pinebook", "https://pine64.org/pinebook");
add_word(&hardware_links, "starlabs", "https://ca.starlabs.systems");
add_word(&hardware_links, "system76", "https://system76.com");
add_word(&hardware_links, "blloc_phone", "https://www.blloc.com");

Dict operating_system_links = create_dict("operating_system_links");
add_word(&operating_system_links, "freebsd", "https://wiki.freebsd.org/FreeBSD/arm/Raspberry%20Pi");
add_word(&operating_system_links, "linux_from_scratch", "http://intestinate.com/pilfs");
add_word(&operating_system_links, "elementaryos", "https://elementary.io");
add_word(&operating_system_links, "osmc", "https://osmc.tv/download");
add_word(&operating_system_links, "genera_os", "https://static.loomcom.com/genera/genera-install.html");
add_word(&operating_system_links, "collapse_os", "https://collapseos.org");
add_word(&operating_system_links, "urbit", "http://urbit.org");
add_word(&operating_system_links, "replicant", "https://www.replicant.us");

Dict plan9_links = create_dict("plan9_links");
add_word(&plan9_links, "plan9_wiki", "https://9p.io/wiki/plan9/plan_9_wiki");
add_word(&plan9_links, "plan9_intro", "http://lsub.org/who/nemo/9.intro.pdf");
add_word(&plan9_links, "plan9_newbie_guide", "http://covingtoninnovations.com/michael/newbie-guide.pdf");
add_word(&plan9_links, "plan9_tutorial", "https://github.com/nspool/hello-plan9");
add_word(&plan9_links, "plan9_audio", "http://nopenopenope.net/posts/audio");
add_word(&plan9_links, "plan9_git", "https://bitbucket.org/oridb/git9/src/default");
add_word(&plan9_links, "plan9_scheme", "http://t3x.org/s9fes");
add_word(&plan9_links, "plan9_ocaml", "http://mirtchovski.com/p9/ocaml");
add_word(&plan9_links, "plan9_window_manager", "https://github.com/zv/9Problems");
add_word(&plan9_links, "acme_screencast", "https://research.swtch.com/acme");
add_word(&plan9_links, "acme_readme", "http://acme.cat-v.org/readme");

Dict programming_links = create_dict("programming_links");
add_word(&programming_links, "bell_labs", "http://doc.cat-v.org/bell_labs");
add_word(&programming_links, "richard_miller", "https://youtube.com/watch?v=O7ZELOUIyvw");
add_word(&programming_links, "rob_pike", "https://usesthis.com/interviews/rob.pike/");
add_word(&programming_links, "unix_translation", "https://9p.io/wiki/plan9/Unix_to_Plan_9_command_translation/index.html");
add_word(&programming_links, "the_humble_programmer", "https://www.cs.utexas.edu/~EWD/transcriptions/EWD03xx/EWD340.html");
add_word(&programming_links, "lisp_eval", "http://lib.store.yahoo.net/lib/paulgraham/jmc.lisp");
add_word(&programming_links, "the_history_of_t", "http://www.paulgraham.com/thist.html");
add_word(&programming_links, "suckless", "https://suckless.org/rocks");
add_word(&programming_links, "build_your_own_lisp", "http://buildyourownlisp.com");
add_word(&programming_links, "interesting_programming_languages", "https://www.btbytes.com/pl.html");

Dict solarpunk_links = create_dict("solarpunk_links");
add_word(&solarpunk_links, "low_tech", "https://solar.lowtechmagazine.com");
add_word(&solarpunk_links, "ce_manifesto", "http://criticalengineering.org");
add_word(&solarpunk_links, "eflux", "https://e-flux.com/architecture/positions/191258/is-ornamenting-solar-panels-a-crime");
add_word(&solarpunk_links, "hieroglyph", "https://hieroglyph.asu.edu/2014/09/Solarpunk-notes-toward-a-manifesto");
add_word(&solarpunk_links, "winnebiko_ii", "https://microship.com/winnebiko-ii");
add_word(&solarpunk_links, "paris_compressed_air_power_network", "http://douglas-self.com/MUSEUM/POWER/airnetwork/airnetwork.htm");
add_word(&solarpunk_links, "deep_resource", "https://deepresource.wordpress.com");
add_word(&solarpunk_links, "design_lifecycle", "http://www.designlife-cycle.com");
add_word(&solarpunk_links, "open_structures", "https://openstructures.net");
add_word(&solarpunk_links, "what_can_a_technologist", "http://worrydream.com/ClimateChange");

Dict personal_wiki_links = create_dict("personal_wiki_links");
add_word(&personal_wiki_links, "gwern", "http://gwern.net");
add_word(&personal_wiki_links, "bayles_shanks", "http://bayleshanks.com");
add_word(&personal_wiki_links, "nikita_voloboev", "https://wiki.nikitavoloboev.xyz");
add_word(&personal_wiki_links, "android_arts", "http://androidarts.com");
add_word(&personal_wiki_links, "b_rye", "http://jbr.me.uk/contents.html");
add_word(&personal_wiki_links, "yoshua_wuyts", "https://github.com/yoshuawuyts/knowledge");
add_word(&personal_wiki_links, "gordon_brander", "http://gordonbrander.com/pattern/");

Dict wiki_links = create_dict("wiki_links");
add_word(&wiki_links, "rational_wiki", "https://rationalwiki.org");
add_word(&wiki_links, "cat_v", "http://doc.cat-v.org/plan_9");
add_word(&wiki_links, "altaplana", "https://altaplana.be");
add_word(&wiki_links, "lo_jbobau", "https://jbo.wikipedia.org/wiki/lo_jbobau");

Dict podcast_links = create_dict("podcast_links");
add_word(&podcast_links, "80000_hours", "https://80000hours.org/podcast");
add_word(&podcast_links, "emerge_podcast", "https://anchor.fm/emerge/support");
add_word(&podcast_links, "90p_invisible", "https://99percentinvisible.org");
add_word(&podcast_links, "lexicon_valley", "https://slate.com/podcasts/lexicon-valley");
add_word(&podcast_links, "radiolab", "https://www.wnycstudios.org/podcasts/radiolab");
add_word(&podcast_links, "love_and_radio", "http://loveandradio.org");
add_word(&podcast_links, "the_future_of_coding", "https://futureofcoding.org");

Dict blog_links = create_dict("blog_links");
add_word(&blog_links, "slate_star_codex", "http://slatestarcodex.com");
add_word(&blog_links, "ribbon_farm", "http://ribbonfarm.com");
add_word(&blog_links, "lesswrong", "https://lesswrong.com");
add_word(&blog_links, "drew_devault", "https://drewdevault.com");
add_word(&blog_links, "fogus", "http://blog.fogus.me");
add_word(&blog_links, "jeff_atwood", "https://blog.codinghorror.com");

Dict entries_links = create_dict("entries_links");
add_word(&entries_links, "the_second_story_of_echo_and_narcissus", "https://thelastpsychiatrist.com/2012/10/the_story_of_narcissus.html");
add_word(&entries_links, "tendrils_of_mess_in_our_brains", "https://www.ribbonfarm.com/2017/01/05/tendrils-of-mess-in-our-brains");
add_word(&entries_links, "meditations_on_moloch", "https://slatestarcodex.com/2014/07/30/meditations-on-moloch");
add_word(&entries_links, "the_tower", "https://hotelconcierge.tumblr.com/post/162571849189/the-tower");
add_word(&entries_links, "culture_is_not_about_esthetics", "https://www.gwern.net/Culture-is-not-about-Esthetics");
add_word(&entries_links, "aquisition_of_the_sibylline_books", "http://nichtdiesetone.blogspot.com/2009/10/sibylline-books.html");
add_word(&entries_links, "the_fable_of_the_dragontyrant", "https://nickbostrom.com/fable/dragon.html");
add_word(&entries_links, "green_days_in_brunei", "http://e-reading.mobi/chapter.php/71789/6/Sterling_-_Crystal_Express.html");
add_word(&entries_links, "bus_ticket_theory", "http://paulgraham.com/genius.html");
add_word(&entries_links, "personal_search_infrastructure", "https://beepb00p.xyz/pkm-search.html");

Dict collapsology_links = create_dict("collapsology_links");
add_word(&collapsology_links, "dark_mountain_manifesto", "https://dark-mountain.net/about/manifesto");
add_word(&collapsology_links, "effective_altruism_forum", "https://forum.effectivealtruism.org");

Dict general_knowledge_links = create_dict("general_knowledge_links");
add_word(&general_knowledge_links, "nutritional_facts", "http://nutritionfacts.org");
add_word(&general_knowledge_links, "as_we_may_think", "https://en.wikipedia.org/wiki/As_We_May_Think");
add_word(&general_knowledge_links, "notation", "https://github.com/hypotext/notation");
add_word(&general_knowledge_links, "funetfipub", "http://nic.funet.fi/pub");
add_word(&general_knowledge_links, "handeye_dilemma", "https://paintedjournals.com/marc-dalessios-learning-curve");
add_word(&general_knowledge_links, "how_to_ask_questions", "http://catb.org/~esr/faqs/smart-questions.html");
add_word(&general_knowledge_links, "janki_method", "http://jackkinsella.ie/articles/janki-method");
add_word(&general_knowledge_links, "chorded_keyboard", "https://software-lab.de/penti.html");
add_word(&general_knowledge_links, "how_to_make_sense_of_any_mess", "http://www.howtomakesenseofanymess.com");

Dict software_links = create_dict("software_links");
add_word(&software_links, "micro_text_editor", "https://micro-editor.github.io");
add_word(&software_links, "fish_shell", "https://fishshell.com");
add_word(&software_links, "nnn_file_manager", "https://github.com/jarun/nnn");
add_word(&software_links, "cmus_audio_player", "http://cmus.github.io");
add_word(&software_links, "spreadsheet_calculator", "https://github.com/andmarti1424/sc-im");
add_word(&software_links, "kdenlive_video_editor", "https://kdenlive.org/en");
add_word(&software_links, "krita_digital_painting", "https://krita.org/en");
add_word(&software_links, "blender_3d_editor", "https://www.blender.org");
add_word(&software_links, "next_web_browser", "https://github.com/atlas-engineer/next");
add_word(&software_links, "ardour_audio_recording", "https://ardour.org");
add_word(&software_links, "cozy_audiobook_player", "https://cozy.geigi.de");
add_word(&software_links, "sunvox_synthesizer", "https://www.warmplace.ru/soft/sunvox");

Dict books = create_dict("books");
add_word(&books, "le_matin_des_magiciens", "L. Pauwels & J. Bergier. 1960");
add_word(&books, "le_citt_invisibili", "Italo Calvino. 1972");
add_word(&books, "ficciones", "Jorge Luis Borges. 1941");
add_word(&books, "no44", "Mark Twain. 1916");
add_word(&books, "kybalion", "Three Initiates. 1908");
add_word(&books, "la_ricerca_della_lingua_perfetta", "Umberto Eco. 1993");
add_word(&books, "the_handmaids_tale", "Margaret Atwood. 1985");
add_word(&books, "flatland", "Edwin A. Abbott. 1884");
add_word(&books, "blumroch_ladmirable", "Louis Pauwels. 1976");
add_word(&books, "cyberiada", "Stanisław Lem. 1965");
add_word(&books, "the_book_of_tea", "Okakura Kakuzō. 1906");
add_word(&books, "journals", "Henry David Thoreau. 1837");
add_word(&books, "etidorhpa", "John Uri Lloyd. 1895");
add_word(&books, "ishmael", "Daniel Quinn. 1992");

Dict movies = create_dict("movies");
add_word(&movies, "rosencrantz_and_guildenstern_are_dead", "Tom Stoppard. 1990");
add_word(&movies, "solaris", "Steven Soderbergh. 2002");
add_word(&movies, "wristcutters_a_love_story", "Goran Dukic. 2006");
add_word(&movies, "the_rules_of_attraction", "Roger Avary. 2002");
add_word(&movies, "faust", "Jan Švankmajer. 1994");
add_word(&movies, "__", "Pen-Ek Ratanaruang. 2003");
add_word(&movies, "my_dinner_with_andre", "Louis Malle. 1981");
add_word(&movies, "sedmikrsky", "Věra Chytilová. 1996");
add_word(&movies, "valerie_a_tden_div", "Jaromil Jireš. 1970");
add_word(&movies, "__", "Sergei Parajanov. 1967");
add_word(&movies, "na_srebrnym_globie", "Andrzej Żuławski. 1988");
add_word(&movies, "", "Katsuhito Ishii. 2004");
add_word(&movies, "cat_soup", "Tatsuo Satō. 2001");

Dict albums = create_dict("albums");
add_word(&albums, "weighing_souls_with_sand", "Angelic Process. 2007");
add_word(&albums, "lunivers_de_la_mer", "Dominique Guiot. 1978");
add_word(&albums, "void", "Access to Arasaka. 2010");
add_word(&albums, "you_have_already_gone_to_the_other_world", "A Hawk & A Hacksaw. 2013");
add_word(&albums, "", "Сруб. 2015");
add_word(&albums, "", "友川カズキ. 2002");
add_word(&albums, "noise_of_the_new", "Seven Ark. 2005");
add_word(&albums, "", "山崎ハコ. 1979");
add_word(&albums, "le_soleil_noir", "Barbara. 1970");
add_word(&albums, "ariettes_oublies", "Les Discrets. 2012");
add_word(&albums, "il_y_a", "夢中夢. 2008");
add_word(&albums, "", "黒百合姉妹. 1999");
add_word(&albums, "", "J.A.シーザー. 2002");
add_word(&albums, "franois", "Desireless. 1989");
add_word(&albums, "head_over_heels", "Cocteau Twins. 1983");

Dict comics = create_dict("comics");
add_word(&comics, "brsel", "Schuiten & Peeters. 1992");
add_word(&comics, "", "弐瓶勉. 1998");
add_word(&comics, "", "宮崎駿. 1982");
add_word(&comics, "", "浅野いにお. 2007");
add_word(&comics, "", "伊藤潤二. 1998");
add_word(&comics, "duck_death_and_the_tulip", "Wolf Erlbruch. 2007");

Dict videogames = create_dict("videogames");
add_word(&videogames, "eve_online", "CCP Games. 2003");
add_word(&videogames, "jet_set_radio_future", "Smilebit. 2002");
add_word(&videogames, "final_fantasy_tactics_advance", "Square. 2003");
add_word(&videogames, "quake_3", "Id. 1999");
add_word(&videogames, "drowned_god", "Inscape. 1997");
add_word(&videogames, "ikaruga", "Treasure. 2001");
add_word(&videogames, "journey", "ThatGameCompany. 2012");
add_word(&videogames, "mdk", "Shiny. 1997");
add_word(&videogames, "riven", "Cyan Interactive. 1997");

Dict reading_list_2016 = create_dict("reading_list_2016");
add_word(&reading_list_2016, "seraffyns_oriental_adventure", "Lin & Larry Pardey");
add_word(&reading_list_2016, "guns_germs__steel", "Jared M. Diamond");
add_word(&reading_list_2016, "predictable_irrational", "Dan Ariely");
add_word(&reading_list_2016, "how_not_to_die", "Michael Greger");
add_word(&reading_list_2016, "the_china_study", "T. Colin Campbell");
add_word(&reading_list_2016, "letter_to_my_father", "Franz Kafka");
add_word(&reading_list_2016, "le_ton_beau_de_marot", "Douglas Hofstadter");
add_word(&reading_list_2016, "beyond_good__evil", "Friedrich Nietzche");
add_word(&reading_list_2016, "the_circle", "Dave Eggers");

Dict reading_list_2017 = create_dict("reading_list_2017");
add_word(&reading_list_2017, "pictures_from_the_water_trade", "John David Morley");
add_word(&reading_list_2017, "a_calendar_of_wisdom", "Tolstoy");
add_word(&reading_list_2017, "the_art_of_war", "Sun Tzu");
add_word(&reading_list_2017, "superintelligence", "Nick Bostrom");
add_word(&reading_list_2017, "kokoro", "Natsume Soseki");
add_word(&reading_list_2017, "from_ai_to_zombies", "Eliezer Yudkowsky");
add_word(&reading_list_2017, "in_praise_of_darkness", "Jorge Luis Borges");
add_word(&reading_list_2017, "selfsufficient_sailor", "Lin Pardey");
add_word(&reading_list_2017, "travels_in_hyperreality", "Umberto Eco");
add_word(&reading_list_2017, "north_to_the_night", "Alvah Simon");
add_word(&reading_list_2017, "smoke_gets_in_your_eyes", "Caitlin Doughty");
add_word(&reading_list_2017, "the_fungi_of_yuggot", "H. P. Lovecraft");
add_word(&reading_list_2017, "in_the_dust_of_this_planet", "Eugene Thacker");
add_word(&reading_list_2017, "the_japanese_art_of_decluttering", "Marie Kondo");
add_word(&reading_list_2017, "zen_and_the_art_of_motorcycle_maintenance", "Robert M. Pirsig");
add_word(&reading_list_2017, "meditations", "Marcus Aurelius");

Dict reading_list_2018 = create_dict("reading_list_2018");
add_word(&reading_list_2018, "hermeneutics", "John D. Caputo");
add_word(&reading_list_2018, "tao_te_ching", "Lao Tzu");
add_word(&reading_list_2018, "letters_from_a_stoic", "Seneca");
add_word(&reading_list_2018, "animal_farm", "George Orwell & Russel Baker");
add_word(&reading_list_2018, "last_chance_to_see", "Douglas Adams & Mark Carwardine");
add_word(&reading_list_2018, "the_arabian_nights", "Anonymous");
add_word(&reading_list_2018, "the_stack", "Benjamin H. Bratton");
add_word(&reading_list_2018, "the_futurological_congress", "Stanislaw Lem");
add_word(&reading_list_2018, "the_handmaids_tale", "Margaret Atwood");
add_word(&reading_list_2018, "the_cyberiad", "Stanislaw Lem");
add_word(&reading_list_2018, "ishmael", "Daniel Quinn");
add_word(&reading_list_2018, "godforsaken_sea", "Derek Lundy");
add_word(&reading_list_2018, "the_tao_of_pooh", "Benjamin Hoff");
add_word(&reading_list_2018, "the_te_of_piglet", "Benjamin Hoff");
add_word(&reading_list_2018, "the_book_of_five_rings", "Miyamoto Musashi");
add_word(&reading_list_2018, "hagakure", "Tsunetomo Yamamoto");
add_word(&reading_list_2018, "dont_sleep_there_are_snakes", "Daneil L. Everett");
add_word(&reading_list_2018, "on_trails", "Robert Moor");
add_word(&reading_list_2018, "the_sixth_extinction", "Elizabeth Kolbert");
add_word(&reading_list_2018, "the_empty_mirror", "Janwillem Van De Wetering");
add_word(&reading_list_2018, "industrial_society_and_its_future", "Theodore Kaczynski");
add_word(&reading_list_2018, "animal_liberation", "Peter Signer");
add_word(&reading_list_2018, "on_food_and_cooking", "Harold McGee");
add_word(&reading_list_2018, "finite_and_infinite_games", "James P. Carse");

Dict reading_list_2019 = create_dict("reading_list_2019");
add_word(&reading_list_2019, "who_owns_the_future", "Jaron Lanier");
add_word(&reading_list_2019, "practical_ethics", "Peter Signer");
add_word(&reading_list_2019, "cyclonopedia", "Reza Negarestani");
add_word(&reading_list_2019, "embassytown", "China Miéville");
add_word(&reading_list_2019, "the_art_of_unix_programming", "Eric S. Raymond");
add_word(&reading_list_2019, "xenofeminism", "Helen Hester");
add_word(&reading_list_2019, "land_of_lisp", "Conrad Barski");
add_word(&reading_list_2019, "the_word_for_world_is_forest", "Ursula K. Le Guin");
add_word(&reading_list_2019, "the_accelerationist_reader", "Robin Mackay");
add_word(&reading_list_2019, "collected_shorts", "H. P. Lovecraft");
add_word(&reading_list_2019, "assemblage_theory", "Manuel DeLanda");
add_word(&reading_list_2019, "rasselas", "Samuel Johnson");
add_word(&reading_list_2019, "inventing_the_future", "Nick Srnicek");
add_word(&reading_list_2019, "the_golden_apples_of_the_sun", "Ray Bradbury");
add_word(&reading_list_2019, "manuel_de_rsistance_contemporaine", "Cyril Dion");
add_word(&reading_list_2019, "girls_last_tour", "Tsukumizu");
add_word(&reading_list_2019, "persepolis", "Marjane Satrapi");
add_word(&reading_list_2019, "how_to_do_nothing", "Jenny Odell");
add_word(&reading_list_2019, "the_complete_cosmicomics", "Italo Calvino");
add_word(&reading_list_2019, "la_socit_du_spectacle", "Guy Debord");